---
language: ruby
cache: bundler
rvm: 
  - 2.1.2
addons:
  postgresql: "9.3"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
